"""create tasks table

Revision ID: 46eba9cb767d
Revises:
Create Date: 2026-10-03 11:47:50.738450

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46eba9cb767d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'tasks',
		sa.Column('title', sa.String(), nullable=False),
		sa.Column('compile', sa.Boolean(), nullable=False),
		sa.Column('id', sa.String(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('tasks')
	# ### end Alembic commands ###
