"""fix tasks table

Revision ID: dc3515de463f
Revises: 46eba9cb767d
Create Date: 2026-10-03 12:36:11.930684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc3515de463f'
down_revision: str | Sequence[str] | None = '46eba9cb767d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False))
	op.drop_column('tasks', 'compile')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('tasks', sa.Column('compile', sa.BOOLEAN(), autoincrement=False, nullable=False))
	op.drop_column('tasks', 'completed')
	# ### end Alembic commands ###
