"""create_production_tables

Revision ID: 58baa4fc4dae
Revises: 
Create Date: 2026-10-06 15:42:41.883304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58baa4fc4dae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_downtimes'))
    )
    op.create_index(op.f('ix_downtimes_record_date'), 'downtimes', ['record_date'], unique=False)
    op.create_table('monthly_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('target_monthly', sa.Integer(), nullable=False),
    sa.Column('produced_fact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_plans')),
    sa.UniqueConstraint('model_name', name=op.f('uq_monthly_plans_model_name'))
    )
    op.create_table('production_lines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_lines'))
    )
    op.create_table('shift_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.Integer(), nullable=True),
    sa.Column('fact', sa.Integer(), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('load_percent', sa.Float(), nullable=False),
    sa.Column('defects_count', sa.Integer(), nullable=True),
    sa.Column('defect_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], name=op.f('fk_shift_metrics_line_id_production_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_metrics'))
    )
    op.create_index(op.f('ix_shift_metrics_record_date'), 'shift_metrics', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_metrics_record_date'), table_name='shift_metrics')
    op.drop_table('shift_metrics')
    op.drop_table('production_lines')
    op.drop_table('monthly_plans')
    op.drop_index(op.f('ix_downtimes_record_date'), table_name='downtimes')
    op.drop_table('downtimes')
    # ### end Alembic commands ###
